version: "3.8"

services:
  db:
    env_file:
      - ./config/docker_dev.env
    image: postgres:14.0
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
