version: 2
jobs:
  test_server:
    docker:
      - image: cimg/elixir:1.8.1
      - image: postgres:11.2-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-deps-cache-{{ checksum "server/mix.lock" }}
            - v3-deps-cache
      - run:
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
            mix deps.compile
            MIX_ENV=test mix deps.compile
          working_directory: server
      - save_cache:
          key: v3-deps-cache-{{ checksum "server/mix.lock" }}
          paths:
            - server/_build
            - server/deps
            - ~/.mix
      - restore_cache:
          keys:
            - v2-plt-cache-{{ checksum "server/mix.lock" }}
            - v2-plt-cache
      - run:
          command: mix dialyzer --plt
          working_directory: server
      - save_cache:
          key: v2-plt-cache-{{ checksum "server/mix.lock" }}
          paths:
            - server/_build
            - ~/.mix
      - run:
          command: |
            mix compile
            MIX_ENV=test mix compile
            mix validate
          working_directory: server
  test_client:
    docker:
      - image: cimg/node:10.15.3
    steps:
      - checkout
      - restore-cache:
          keys:
            - v1-node-deps-cache-{{ checksum "client/package-lock.json" }}
            - v1-node-deps-cache
      - run:
          command: npm install
          working_directory: client
      - save_cache:
          key: v1-node-deps-cache-{{ checksum "client/package-lock.json" }}
          paths:
            - client/node_modules
      - run:
          command: npm run validate
          working_directory: client
  # test_e2e:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: docker-compose up --build e2e_test e2e
  #     - store_artifacts:
  #         path: ./e2e/cypress/screenshots
workflows:
  version: 2
  test_all:
    jobs:
      - test_server
      - test_client
      # - test_e2e
