version: 2.1
parameters:
  cache-version:
    default: v2
    type: string
  elixir:
    type: string
    default: 1.16.0
  postgres:
    type: string
    default: "15.1"
jobs:
  test:
    docker:
      - image: cimg/elixir:<< pipeline.parameters.elixir >>
      - image: postgres:<< pipeline.parameters.postgres >>
        environment:
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - <<pipeline.parameters.cache-version>>-deps-<<pipeline.parameters.elixir>>-{{ checksum "mix.lock" }}
            - <<pipeline.parameters.cache-version>>-deps-<<pipeline.parameters.elixir>>
            - <<pipeline.parameters.cache-version>>-deps
      - run:
          name: Install dependencies
          command: |
            mix local.hex --force --if-missing
            mix local.rebar --force
            mix deps.get
      - run:
          name: Compile dependencies for dev
          command: mix deps.compile
      - run:
          name: Compile dependencies for test
          command: mix deps.compile
          environment:
            MIX_ENV: test
      - run:
          command: mix dialyzer --plt
          environment:
            MIX_ENV: test
      - save_cache:
          key: <<pipeline.parameters.cache-version>>-deps-<<pipeline.parameters.elixir>>-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - restore_cache:
          keys:
            - <<pipeline.parameters.cache-version>>-compile-<<pipeline.parameters.elixir>>-{{ checksum "mix.lock" }}
      - run:
          name: Compile for dev
          command: mix compile
      - run:
          name: Compile for test
          command: mix compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: <<pipeline.parameters.cache-version>>-compile-<<pipeline.parameters.elixir>>-{{ checksum "mix.lock" }}
          paths:
            - _build
      - run:
          name: Run validations
          command: mix validate
      - store_test_results:
          path: _build/test/lib/freedom_account/test-junit-report.xml

workflows:
  test_all:
    jobs:
      - test

# VS Code Extension Version: 1.2.2
