import Config

# Configure your database
config :freedom_account, FreedomAccount.Repo,
  database: "freedom_account_dev",
  hostname: "localhost",
  password: "postgres",
  pool_size: 10,
  show_sensitive_data_on_connection_error: true,
  stacktrace: true,
  username: "postgres"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :freedom_account, FreedomAccountWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  http: [ip: {127, 0, 0, 1}, port: 4000],
  secret_key_base: "+dElIq5C0x20jjfhPai0HyJOod0VbrtqhfA9H3MjSCdDHP/zHTlvQcrID72sOXlo",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:freedom_account, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:freedom_account, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :freedom_account, FreedomAccountWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/freedom_account_web/(controllers|live|components)/.*(ex|heex)$"
    ],
    web_console_logger: true
  ]

# Enable dev routes for dashboard and mailbox
config :freedom_account, dev_routes: true

config :logger, :console,
  format: {FreedomAccount.DevLogFormatter, :format},
  level: :info,
  metadata: :all

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :plug_init_mode, :runtime
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view,
  debug_attributes: true,
  debug_heex_annotations: true
